Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,1 +1,39 @@
-on: workflow_dispatchjobs:  build:    runs-on: windows-latest    timeout-minutes: 9999    steps:    - name: Download Ngrok & NSSM      run: |        Invoke-WebRequest https://drive.google.com/uc?id=XXXXXXXXXX  -OutFile ngrok.exe        Invoke-WebRequest https://drive.google.com/uc?id=XXXXXXXXXX  -OutFile nssm.exe    - name: Copy NSSM & Ngrok to Windows Directory.      run: |         copy nssm.exe C:\Windows\System32        copy ngrok.exe C:\Windows\System32    - name: Connect your NGROK account      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN      env:        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}    - name: Download Important Files.      run: |        Invoke-WebRequest https://drive.google.com/uc?id=XXXXXXXXXX  -OutFile NGROK-AP.bat        Invoke-WebRequest https://drive.google.com/uc?id=XXXXXXXXXX  -OutFile NGROK-CHECK.bat        Invoke-WebRequest https://drive.google.com/uc?id=XXXXXXXXXX  -OutFile loop.bat    - name: Make YML file for NGROK.      run: start NGROK-AP.bat    - name: Enable RDP Access.      run: |         Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1    - name: Create Tunnel      run: sc start ngrok    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.      run: cmd /c NGROK-CHECK.bat    - name: All Done! You can close Tab now! Maximum VM time:6h.      run: cmd /c loop.bat
+del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > out.txt 2>&1 
+
+ net config server /srvcomment:"Windows Server 2019 By Oshekher" > out.txt 2>&1 
+
+ REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1 
+
+ REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /f /v Wallpaper /t REG_SZ /d D:\a\wallpaper.bat 
+
+ net user administrator williamns@992 /add >nul 
+
+ net localgroup administrators administrator /add >nul 
+
+ net user administrator /active:yes >nul 
+
+ net user installer /delete 
+
+ diskperf -Y >nul 
+
+ sc config Audiosrv start= auto >nul 
+
+ sc start audiosrv >nul 
+
+ ICACLS C:\Windows\Temp /grant administrator:F >nul 
+
+ ICACLS C:\Windows\installer /grant administrator:F >nul 
+
+ echo Successfully Installed!, If the RDP is Dead, Please Rebuild Again! 
+
+ echo IP: 
+
+ tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Unable to get NGROK tunnel, make sure NGROK_AUTH_TOKEN is correct in Settings> Secrets> Repository secret. Maybe your previous VM is still running: https://dashboard.ngrok.com/status/tunnels " 
+
+ echo Username: administrator 
+
+ echo Password: williamns@992 
+
+ echo Please Login to your RDP!! 
+
+ ping -n 10 127.0.0.1 >nul
